### ISSUE TITLE
Implement Lumo & Material themes

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-date-time-picker#5]
<img width="284" alt="Screenshot 2019-09-10 at 11 54 18" src="https://user-images.githubusercontent.com/1222264/64600177-5b93b100-d3c3-11e9-8d78-b064a2a35530.png">

**Comment by Haprog** [comment]
We can leave the width of date picker and time picker as is by default for now, but to make it possible to make more horizontally compact field we should introduce some predefined theme variants to control the width of time picker (and maybe also date picker?).

But imo these new theme variants should be implemented within vaadin-time-picker (and optionally vaadin-date-picker) so that they can also be used in those components, and they would automatically be available to use also via setting a theme attribute for vaadin-date-time-picker.

To allow controlling the width of date picker and time picker separately we could e.g. make sure to prefix or suffix those theme variant names with `date`/`time` so we can pass them as is in date-time-picker.

Some ideas for theme variant names for time picker:
- `time-width-hours` ("00:00")
- `time-width-hours-12h` ("00:00 AM")
- `time-width-seconds` ("00:00:00")
- `time-width-seconds-12h` ("00:00:00 AM")
- `time-width-milliseconds` ("00:00:00.000")

Date picker could have similar variants for some most common date formats

**Comment by jouni** [comment]
Yes, I agree that these variants should be in the contained components, not just date-time-picker. 

`time-width-hours` should IMO be `time-width-mins` instead, as it is showing minutes as well.

What happens when an explicit width is set on the date-time-picker? How do the fields shrink/grow?

**Comment by Haprog** [comment]
> time-width-hours should IMO be time-width-mins instead, as it is showing minutes as well.

That's what I meant to write but somehow wrote hours instead. :)
